[package]
name = "ali_oss"
version = "0.1.0"
authors = ["shaipe <shaipe@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
base64 = "0.10.1"
sha-1 = "0.8.1"
md-5 = "0.8.0"
